import struct
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import os
import sys

def read_grid_bin(grid_bin_path):
    """
    Reads the grid.bin headers generated by the C++ simulation.
    Binary structure per block:
      - int32_t level
      - int64_t lx1, lx2
      - double  x1min, x1max, x2min, x2max
      - uint64_t nx1, nx2
    """
    blocks = []
    
    header_fmt = "<Q"              # uint64_t nblocks
    block_fmt = "<i q q d d d d Q Q"   # int32, int64*2, double*4, uint64*2
    
    header_size = struct.calcsize(header_fmt)
    block_size = struct.calcsize(block_fmt)
    
    if not os.path.exists(grid_bin_path):
        raise FileNotFoundError(f"Error: {grid_bin_path} not found!")

    with open(grid_bin_path, 'rb') as f:
        header_data = f.read(header_size)
        if len(header_data) < header_size:
            raise ValueError("The grid.bin file is corrupted or empty.")
        
        nblocks, = struct.unpack(header_fmt, header_data)
        
        for _ in range(nblocks):
            block_data = f.read(block_size)
            if len(block_data) < block_size:
                break
            
            level, lx1, lx2, x1min, x1max, x2min, x2max, nx1, nx2 = struct.unpack(block_fmt, block_data)
            
            blocks.append({
                'level': level,
                'lx1': lx1,
                'lx2': lx2,
                'x1min': x1min,
                'x1max': x1max,
                'x2min': x2min,
                'x2max': x2max,
                'nx1': nx1,
                'nx2': nx2
            })
            
    return blocks

def plot_mesh_blocks_from_grid_bin(grid_bin_path, output_image="mesh_structure.png"):
    """
    Plots only the outlines of the mesh blocks directly from grid.bin.
    """
    blocks = read_grid_bin(grid_bin_path)
    if not blocks:
        print("No blocks found to plot!")
        return

    levels = sorted(list(set(b['level'] for b in blocks)))

    fig, ax = plt.subplots(figsize=(12, 8), facecolor='white')
    ax.set_facecolor('white')

    xmin = min(b['x1min'] for b in blocks)
    xmax = max(b['x1max'] for b in blocks)
    ymin = min(b['x2min'] for b in blocks)
    ymax = max(b['x2max'] for b in blocks)

    for b in blocks:
        x0 = b['x1min']
        y0 = b['x2min']
        width = b['x1max'] - b['x1min']
        height = b['x2max'] - b['x2min']
        lvl = b['level']

        # facecolor='none' makes the inside transparent, leaving only outlines
        rect = patches.Rectangle(
            (x0, y0), width, height,
            linewidth=0.8 + 0.3 * lvl,
            edgecolor='black',
            facecolor='none',
            zorder=lvl + 2
        )
        ax.add_patch(rect)

    margin_x = (xmax - xmin) * 0.03
    margin_y = (ymax - ymin) * 0.03
    ax.set_xlim(xmin - margin_x, xmax + margin_x)
    ax.set_ylim(ymin - margin_y, ymax + margin_y)

    ax.set_xlabel('X', fontsize=12)
    ax.set_ylabel('Y', fontsize=12)
    ax.set_title(f'Static Mesh Refinement Outlines (Total blocks: {len(blocks)})', fontsize=14)
    ax.grid(True, linestyle='--', alpha=0.3, color='gray')

    plt.tight_layout()
    plt.savefig(output_image, dpi=300, bbox_inches='tight')
    print(f"Mesh outline image successfully saved to: {output_image}")
    plt.show()

if __name__ == "__main__":
    grid_file = "Sod_shock_tube/grid.bin"
    if len(sys.argv) > 1:
        grid_file = sys.argv[1]

    plot_mesh_blocks_from_grid_bin(grid_file)
